### ISSUE TITLE
Support for Embeddium 0.3.x

### ISSUE THREAD

**Issue by UltimatChamp** [ferriarnus/acedium#6]
**Embeddium `0.3.0`** is based on  **Sodium `0.5.6`**/**7**, which has brought a lot of changes.

The parent repository **Nvidium** has also not been updated to support **Sodium `0.5.6`**, at the time of writing, so, not expecting you to rush through it.

***

**Mods:**
Acedium `0.2.5-beta`
Embeddium `0.3.0+mc1.20.1`

***

**Crash Report:**
The game does not crash, but the terrain does not render (entities too). Same behaviour as Nvidium on Fabric.

Here's a piece of log that keeps on bloating it with 1000s of lines:
```
Error doing traversal
java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.chunk.occlusion.OcclusionCuller.findVisible(java.util.function.Consumer, me.jellysquid.mods.sodium.client.render.viewport.Viewport, float, boolean, int)'
    at TRANSFORMER/acedium@0.2.5-beta/me.cortex.nvidium.managers.AsyncOcclusionTracker.run(AsyncOcclusionTracker.java:97)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by UltimatChamp** [comment]
**Update:** **Nvidium** has now been updated to support **Sodium `0.5.6+`**!
